### ISSUE TITLE
create-realm: mints supply error

### ISSUE THREAD

**Issue by dahifi** [blockworks-foundation/governance-ui#79]
The number of decimals in the token supply * the decimals cannot exceed 16, else it throws an error `Number can only safely store up to 53 bits`

For example, create a community mint with the default 9 decimals, then mint 10_000_000 tokens. 

```
pages/realms/new.tsx:152:
  const handleCommunityMint = async (mintId) => {
    handleSetForm({
      communityMintId: mintId,
      communityMint: undefined,
    })
    try {
      const mintPublicKey = new PublicKey(mintId)
      const mint = await tryGetMint(connection.current, mintPublicKey)
      console.log("tryGetMint");
      if (mint) {
        console.log("mint!.account.supply", mint!.account.supply);
        const supply = mint!.account.supply.toNumber()
        try {
          const supply = mint!.account.supply.toNumber()
        } catch (e) {
          console.log('failed to get mint supply', e)
        }
        ```

I'm not sure the best way to resolve this. Maybe leaving supply as a BN will do the trick, will have to trace the code and see how many changes are needed.

**Comment by SebastianBor** [comment]
In general case converting u64 toNumber() is not safe (as you just witnessed) we work around it by using BigNumber. 
You should also use operations which don't result in losing precision, so use shiftBy() mint decimal places instead of multiplying/dividing . Check the code in units.tx for useful helpers

**Comment by jpbogle** [comment]
Thanks for filing @dahifi

Should be fixed with commit https://github.com/blockworks-foundation/governance-ui/commit/19331b660c6f931806ae70f6fc8f04a5a63e11ac
