### ISSUE TITLE
Cluster navigation button

### ISSUE THREAD

**Issue by dahifi** [blockworks-foundation/governance-ui#84]
As a user, I would like to have a button that allows me to switch between mainnet, devnet, and custom RPC endpoints. 
The Solana explorer does this well: 
![image](https://user-images.githubusercontent.com/8903067/142732700-ade25328-271f-4265-838c-1b9ea65354c5.png)
![image](https://user-images.githubusercontent.com/8903067/142732692-de9a016e-d7c1-4e59-b6f5-e9f43b006af0.png)

I'll find the relevant component code and link it here and we can discuss how to implement it in the governance-ui.

**Comment by mschneider** [comment]
Shouldn't be in the top navigation. Useful for development but not needed for end users, network selection should be configured in the local .env file or via url not through the UI
