### ISSUE TITLE
set-realm-config instructions not decoded

### ISSUE THREAD

**Issue by armaniferrante** [blockworks-foundation/governance-ui#87]
See https://dao-beta.mango.markets/dao/SERUM/proposal/FFf16PUCKYZx6PVv6NEgijzQ3hXy1cUbaAzu39R1NvwY

**Comment by dahifi** [comment]
![image](https://user-images.githubusercontent.com/8903067/142889432-222dceb7-58f7-4264-aa51-e37a4e83deb6.png)

**Comment by SebastianBor** [comment]
Fixed by https://github.com/blockworks-foundation/governance-ui/pull/89. Without the governance clone registry we have to keep hardening the known clones. The same problem exists in other generic browsers like Explorer
