### ISSUE TITLE
Create proposal : Instruction/Governance list empy

### ISSUE THREAD

**Issue by solanasail** [blockworks-foundation/governance-ui#90]
Hello.

When created a proposal and instruction, the dropdown list is empty(see screenshot).

It only happens with a single governance, also if there is only one it should be selected by default.
<img width="841" alt="Capture d’écran 2021-11-21 à 00 27 38" src="https://user-images.githubusercontent.com/84818641/142833979-b2aa5b53-f74c-464e-b2cc-eb2d2b638574.png">

**Comment by SebastianBor** [comment]
It seems to be happening only when there is a single governance available. In this case the only governance should be selected by default

**Comment by jpbogle** [comment]
This UI only supports a few instructions currently. If your governance you have has no supported instructions than the list for instructions is empty https://github.com/blockworks-foundation/governance-ui/blob/main/hooks/useInstructions.ts#L53

**Comment by jpbogle** [comment]
nevermind actually with @abrzezinski94 commit here https://github.com/blockworks-foundation/governance-ui/pull/72/files you should see "Execute Custom Instruction"

**Comment by abrzezinski94** [comment]
> nevermind actually with @abrzezinski94 commit here https://github.com/blockworks-foundation/governance-ui/pull/72/files you should see "Execute Custom Instruction"

making fix

**Comment by SebastianBor** [comment]
Fixed by https://github.com/blockworks-foundation/governance-ui/pull/95
