### ISSUE TITLE
Proposal draft : cannot signoff

### ISSUE THREAD

**Issue by solanasail** [blockworks-foundation/governance-ui#91]
Hello,
<img width="1207" alt="Capture d’écran 2021-11-21 à 00 37 26" src="https://user-images.githubusercontent.com/84818641/142834376-af4dde91-78e5-4c0c-9681-5254242797e4.png">

When created a new proposal on the new UI, I cannot signed-off the new proposal.

**Comment by SebastianBor** [comment]
Duplicate https://github.com/blockworks-foundation/governance-ui/issues/86
